config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  devise_scope :user do
    get '/users/verify', to: 'users/sessions#verify'
    post '/users/verify', to: 'users/sessions#check_2fa'
  end
  resources :posts do
    resources :comments
  end
  resources :admin, only: [:index, :destroy]
  namespace 'api' do
    namespace 'v1' do
      resources :posts
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, inverse_of: :posts
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 3 }
  validates :body, presence: true, length: { minimum: 10 }
  validates_presence_of :user
  has_attached_file :post_image, styles: { post_show: '652x393>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :post_image, content_type: /\Aimage\/.*\z/
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      def index
        if params[:created_at].present?
          @posts = Post.where(created_at: Time.zone.parse(params[:created_at]).at_beginning_of_day..Time.zone.parse(params[:created_at]).end_of_day)
        elsif params[:start].present?
          @posts = Post.where(created_at: Time.zone.parse(params[:start]).at_beginning_of_day..Time.zone.parse(params[:end]).end_of_day)
        else
          @posts = Post.order('created_at DESC')
        end
        render json: @posts
      end

      def show
        @post = Post.find(params[:id])
        render json: @post
      end
    end
  end
end

app/controllers/posts_controller.rb
# controller for posts
class PostsController < ApplicationController
  # define before actions to run before any other methods
  before_action :authenticate_user!, only: [:new, :edit, :destroy, :update]
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :check_auth, only: [:edit, :destroy, :update]

  def index
    if params[:user_id].present?
      @posts = Post.where(user_id: params[:user_id]).order('created_at DESC')
    else
      @posts = Post.all.order('created_at DESC')
    end
    @users = User.all
  end

  def show
    @post
  end

  def new
    @post = current_user.posts.build
  end

  def edit
    @post
  end

  def create
    @post = current_user.posts.build(post_params)

    @user = current_user

    if @post.save
      if @user.posts.count <= 1
        # ApplicationMailer.first_post_notification(@user).deliver_later
        # FirstPostMailerJob.perform_later(@user)
        FirstPostMailerJob.delay(@user.id).perform
      end
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :post_image)
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def check_auth
    redirect_to root_path unless current_user.id == @post.user_id
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def belongs_to_user?(post)
    current_user.id == post.user_id
  end

  def admin?(post)
    current_user.admin? && current_user.id != post.user_id
  end

  def image?(post)
    post.post_image.present?
  end
end

app/views/posts/_form.html.haml
= form_for @post do |f|
  .form-group
    = f.label :title
    %br
    = f.text_field(:title, {:class => "form-control"})
  .form-group
    = f.label :body
    %br
    = f.text_area(:body, {:class => "form-control post-body"})
  .form-group
    = f.file_field(:post_image)
  .form-group
    = f.submit "Publish", ({:class => "btn btn-success"})
  - if @post.errors.any?
    - @post.errors.full_messages.each do |msg|
      .alert.alert-danger
        = msg
  

app/views/posts/edit.html.haml
.row
  .col-lg-8
    = render 'form'

app/views/posts/index.html.haml
.row
  .col
    %h1 
      All posts
    %hr
.row
  .col-lg-8
    - @posts.each do |post|
      .card.main-card
        = link_to post.title, post_url(post)
        = post.created_at.strftime('%b %e %Y')
        %span 
          Author: 
          = post.user.name
  .col-lg-4
    .comment-card
      %h4 View posts by author
      - @users.each do |user|
        %div
          = link_to user.name, posts_url(user_id: user.id)

app/views/posts/new.html.haml
.row
  %h1 
    Add a post
.row
  .col-lg-8
    = render 'form'
  = link_to "Back", posts_path

app/views/posts/show.html.haml
.row
  %h1 
    = @post.title
%hr
.row
  .col-lg-8
    .card.post-card
      = @post.body
      - if image?(@post)
        = image_tag @post.post_image.url(:post_show), class: "post-image"
  .col-lg-4
    - if user_signed_in?
      - if belongs_to_user?(@post)
        = link_to "Edit", edit_post_path(@post), class: "btn btn-warning"
        = link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure???" } , class: "btn btn-danger"
      - if admin?(@post)
        = link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure???" } , class: "btn btn-danger"

.row
  .col-lg-10
    %h2.comment-heading
      Leave a comment
%hr
.row
  .col-lg-10
    = render "comments/form"
.row
  = render partial: 'comments/comment', collection: @post.comments