config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  devise_scope :user do
    get '/users/verify', to: 'users/sessions#verify'
    post '/users/verify', to: 'users/sessions#check_2fa'
  end
  resources :posts do
    resources :comments
  end
  resources :admin, only: [:index, :destroy]
  namespace 'api' do
    namespace 'v1' do
      resources :posts
    end
  end
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title 
      Emr Blog
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

%body
  %nav.navbar.navbar-expand-lg.navbar-light.bg-light
    = link_to "EMR Blog", root_path, class: "navbar-brand"
    %button.navbar-toggler{type: "button", 'data-toggle': "collapse", 'data-target': "#navbarNav", 'aria-controls': "navbarNav", 'aria-expanded': "false", 'aria-label': "Toggle navigation"}
      %span.navbar-toggler-icon
    #navbarNav.collapse.navbar-collapse 
      %ul.navbar-nav
        %li.nav-item.active
          = link_to "Home", root_path, class: "nav-link"
        - if user_signed_in?
          %li.nav-item
            = link_to "New Post", new_post_path, class: "nav-link"
          - if current_user.admin?
            %li.nav-item
              = link_to "Admin Pannel", admin_index_path, class: "nav-link"
      %ul.navbar-nav.ml-auto
        - if user_signed_in?
          %li.nav-item
            %a.nav-link.disabled
              = "Welcome, #{current_user.name}"
          %li.nav-item
            = link_to "Logout", destroy_user_session_path, class: "nav-link", method: :delete
        - else
          = link_to "Login", new_user_session_path, class: "nav-link"
          = link_to "Sign Up", new_user_registration_path, class: "nav-link"
  .container
    .row
      .col-lg-4
        - if notice.present?
          %p.notice.alert.alert-primary
            = notice
        - if alert.present?
          %p.alert.alert-danger
            = alert
  .container
    = yield